FROM fukamachi/qlot

WORKDIR /app
COPY . /app
RUN qlot install

FROM fukamachi/sbcl
ENV APP_ENV production
ENV CLACK_HANDLER woo
ENV PORT 80

RUN set -x; \
  apt-get update && apt-get -y install --no-install-recommends \
    gcc \
    libev-dev \
    libyaml-dev && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=0 /app /app

RUN set -x; \
  ros -l .qlot/setup.lisp -e '(ql:quickload (list :clack :woo :quickdocs-api))'

ENTRYPOINT ["/app/docker/entrypoint.sh"]
