name: Build Docker image

on:
  push:
    branches:
      - master
  create:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and publish (tag)
        uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'create' }}
        with:
          context: .
          file: ./docker/Dockerfile.production
          platforms: linux/amd64
          push: true
          addLatest: true
          image: quickdocs/quickdocs-api
      - name: Build and publish
        uses: docker/build-push-action@v2
        if: ${{ github.event_name != 'create' }}
        with:
          context: .
          file: ./docker/Dockerfile.production
          platforms: linux/amd64
          push: true
          tags: |
            quickdocs/quickdocs-api:latest
